name: dartlang_utils
description: A dart package containing a collection of useful util and extension classes.
version: 0.1.0-nullsafety.0
homepage: https://begnis.dev
repository: https://github.com/Dimibe/dartlang_utils/tree/null-safety


environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.0-nullsafety.12
  pedantic: ^1.10.0-nullsafety.3