name: dartlang_utils
description: A dart package containing a collection of useful util and extension classes.
version: 0.2.0
homepage: https://begnis.dev
repository: https://github.com/Dimibe/dartlang_utils/


environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  test: ^1.21.1
  lints: ^2.0.0