name: dartlang_utils
description: A dart package containing a collection of useful util and extension classes.
version: 0.0.3
homepage: https://begnis.dev
repository: https://github.com/Dimibe/dartlang_utils


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.15.6
  pedantic: ^1.9.2